const GET_ALL_POSTS = "GET_ALL_POSTS";
const GET_POST_BY_USERID = "GET_POST_BY_USERID";
const CREATE_POST = "CREATE_POST";
const EDIT_POST = "EDIT_POST";
const LIKE = "LIKE";
const DELETE_POST = "DELETE_POST";

export {CREATE_POST, EDIT_POST, DELETE_POST, GET_ALL_POSTS , GET_POST_BY_USERID, LIKE};