const GET_PROFILE = "GET_PROFILE";
const EDIT_PROFILE = "EDIT_PROFILE";
const FOLLOW_USER = "FOLLOW_USER";
const CLOSE_ACCOUNT = "CLOSE_ACCOUNT";

export { GET_PROFILE , EDIT_PROFILE , FOLLOW_USER , CLOSE_ACCOUNT };